# Generated by Django 2.2.5 on 2019-11-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_table', '0002_recommendeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedItem',
        ),
    ]
