# Generated by Django 2.2.5 on 2019-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_table', '0004_recommendeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topk',
            fields=[
                ('keyword', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('tfidf1', models.FloatField(blank=True, null=True)),
                ('tfidf2', models.FloatField(blank=True, null=True)),
                ('tfidf3', models.FloatField(blank=True, null=True)),
                ('tfidf4', models.FloatField(blank=True, null=True)),
                ('tfidf5', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendResult',
            fields=[
                ('time', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('tweet', models.IntegerField(blank=True, null=True)),
                ('beauty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trend_result',
                'managed': False,
            },
        ),
    ]
